### ISSUE TITLE
Add support for comment based attributes

### ISSUE THREAD

**Issue by Argmaster** [Argmaster/pygerber#118]
Example of one:
```gerber
G04  !@# ... *
```

**Comment by edmccabe5** [comment]
For now, is it best to go through the gerber files and remove any lines with the G04 before sending it to the pygerber parser?

**Comment by Argmaster** [comment]
No, you can leave them as-is, they will be just threated as comments so there will be no way to retrieve them after parsing.

This issue refers to special type of G04 comments which carry standardized attributes instead of only human readable text.

Image should not be affected.
There should be no errors related to G04.
